name: Delete old workflow runs

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Delete old workflow runs
        uses: JuvenileQ/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ChetanSaini726/whack-a-mole
          retain_days: 30
          keep_minimum_runs: 6
